name: Update file

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Latest file
        run: |
          if curl -o public/chaos-bugbounty-list.json https://raw.githubusercontent.com/projectdiscovery/public-bugbounty-programs/refs/heads/main/chaos-bugbounty-list.json; then
            echo "Download successful."
          else
            echo "Download failed."
            exit 1
          fi
          
      - name: Commit and Push Changes if Updated
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are any changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add public/chaos-bugbounty-list.json
            git commit -m "Update file"
            git push origin master
          else
            echo "No changes to commit."
          fi
